name: 'Delete Resource Group'
description: 'Deletes a Resource Group in Azure'
inputs:
  credentials:
    description: 'The Azure credentials to log in'
    required: true
  resource-group-name:
    description: 'The name for the resource group to be deleted'
    required: true
runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ inputs.credentials }}
    
    - name: Delete Resource Group
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az group delete --name ${{ inputs.resource-group-name }} --yes