name: 'Deploy Key Vault'
description: 'Deploy the Key Vault in Azure'
inputs:
  credentials:
    description: 'The Azure credentials to log in'
    required: true
  subscription-id:
    description: 'The subscription that the vault will be created'
    required: true
  resource-group-name:
    description: 'The resource group name that the vault will be created'
    required: true
  resource-name:
    description: 'The resource name that the vault will be created'
    required: true
  environment:
    description: 'The environment that the vault will be created'
    required: true
  location:
    description: 'The region/location for the vault'
    required: true
  database-admin-login:
    description: 'Database Admin Login secret to add in vault'
    required: true
  database-admin-pass:
    description: 'Database Admin Password secret to add in vault'
    required: true
  database-client-ip-value:
    description: 'Database Client Ip Value secret to add in vault'
    required: true
runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ inputs.credentials }}

    - name: Deploy Key Vault
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az deployment group create \
          --name Deploy ${{ inputs.resource-name }} \
          --resource-group ${{ inputs.resource-group-name }} \
          --template-file ./azure/arm-templates/resource/key-vault-template.json \
          --parameters resourceName="${{ inputs.resource-name }}" location="${{ inputs.location }}" @./azure/arm-templates/resource/parameters.json

    - name: Upload Vault Secrets
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az keyvault secret set --vault-name ${{ inputs.resource-name }} --name administratorLogin --value ${{ inputs.database-admin-login }}
          az keyvault secret set --vault-name ${{ inputs.resource-name }} --name administratorLoginPassword --value ${{ inputs.database-admin-pass}}
          az keyvault secret set --vault-name ${{ inputs.resource-name }} --name clientIpValue --value ${{ inputs.database-client-ip-value }}