name: 'Push Image'
description: 'Push a docker image to the Azure Container Registry'
inputs:
  credentials:
    description: 'The Azure credentials to log in'
    required: true
  image-name:
    description: 'The name for the image'
    required: true
  image-tag:
    description: 'The tag for the image'
    required: true
  registry-name:
    description: 'The Azure Container Registry Name'
    required: true
  docker-file-path:
    description: 'The Docker File Path to build the image'
    required: true
runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ inputs.credentials }}

    - name: Push Image
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az acr build --image ${{ inputs.image-name }}:${{ inputs.image-tag }} --registry ${{ inputs.registry-name }} --file ${{ inputs.docker-file-path }}