name: User Acceptance Tests Pipeline

on:
  workflow_run:
    workflows: [ "Test Deploy Pipeline" ] #TODO: passar o nome do workflow
    types:
      - completed
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
  workflow_dispatch:

jobs:
  user-acceptance-tests:
    runs-on: ubuntu-latest
    steps:
     - name: Clone Repo
       uses: actions/checkout@v3
       
     - name: Run Acceptance Tests
       run: dotnet test ./tests/user-interface/TechNews.UI.Tests/TechNews.UI.Tests.csproj #TODO: passar as variáveis de ambiente
