name: Build Pipeline

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  # Build
  build-apps:
    uses: ./.github/workflows/reusable-build.yml
  
  # Unit and Integrations Tests
  run-unit-and-integration-tests:
    needs: [ build-apps ]
    uses: ./.github/workflows/reusable-unit-and-integration-tests.yml
  
  # Setup Testing Environment
  setup-testing-environment:
    needs: [ run-unit-and-integration-tests ]
    uses: ./.github/workflows/reusable-setup-testing-environment.yml
    
  # Run Acceptance Tests
  run-user-acceptance-tests:
    needs: [ setup-testing-environment ]
    uses: ./.github/workflows/reusable-user-acceptance-tests.yml
  
  # Clean up Testing Environment
  cleanup-testing-environment:
    needs: [ run-user-acceptance-tests ]
    uses: ./.github/workflows/reusable-cleanup-testing-environment.yml
    
  # Deploy to Prodution
  deploy-to-production-environment:
    needs: [ run-user-acceptance-tests ]
    uses: ./.github/workflows/reusable-deploy-to-production-environment.yml
