name: Build Pipeline

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  call-workflow-passing-data-1:
    uses: ./.github/workflows/test-reusable.yml@develop
    with:
      username: Everton
      
  call-workflow-passing-data-2:
    uses: ./.github/workflows/test-reusable.yml@develop
    with:
      username: Joyce

