name: Cleanup Testing Environment Reusable Workflow

on:
  workflow_call:

jobs:
  cleanup-testing-environment:
    runs-on: ubuntu-latest
    steps:

      - name: Azure Login
        id: login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Delete Resource Group
        uses: azure/cli@v1
        with:
          max_attempts: 1
          retry_on: error
          azcliversion: latest
          inlineScript: |
            az group delete --name ${{ vars.TEST_RESOURCE_GROUP_NAME }} --yes
