name: Unit Tests Pipeline

on:
  workflow_run:
    workflows: [ "Build Pipeline" ]
    types:
      - completed
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
     - name: Clone Repo
       uses: actions/checkout@v3
       
     - name: Run Auth unit Tests
       run: dotnet test ./tests/unit/TechNews.Auth.Api.Tests/TechNews.Auth.Api.Tests.csproj

     - name: Run Core unit Tests
       run: dotnet test ./tests/unit/TechNews.Core.Api.Tests/TechNews.Core.Api.Tests.csproj
